extends RefCounted
const ALL = [
  {
    "id": "forge_steel",
    "title": "Steel in Your Hands",
    "detail": "Forge your first Steel Sword.",
    "source": "gains",
    "key": "steel_sword",
    "target": 1,
    "gold": 150,
    "food": 10,
    "scrap": 10,
    "activity": "craft_steel_sword"
  },
  {
    "id": "stock_steel",
    "title": "A Stock of Steel",
    "detail": "Gather 50 Magnetite.",
    "source": "gains",
    "key": "steel_ore",
    "target": 50,
    "gold": 100,
    "food": 10,
    "scrap": 5,
    "activity": "mine_steel"
  },
  {
    "id": "forge_moonsteel",
    "title": "Moonsteel in Your Hands",
    "detail": "Forge your first Moonsteel Sword.",
    "source": "gains",
    "key": "moonsteel_sword",
    "target": 1,
    "gold": 300,
    "food": 10,
    "scrap": 20,
    "activity": "craft_moonsteel_sword"
  },
  {
    "id": "stock_moonsteel",
    "title": "A Stock of Moonsteel",
    "detail": "Gather 50 Moonsteel ore.",
    "source": "gains",
    "key": "moonsteel_ore",
    "target": 50,
    "gold": 200,
    "food": 10,
    "scrap": 10,
    "activity": "mine_moonsteel"
  },
  {
    "id": "forge_dusksteel",
    "title": "Dusksteel in Your Hands",
    "detail": "Forge your first Dusksteel Sword.",
    "source": "gains",
    "key": "dusksteel_sword",
    "target": 1,
    "gold": 450,
    "food": 10,
    "scrap": 30,
    "activity": "craft_dusksteel_sword"
  },
  {
    "id": "stock_dusksteel",
    "title": "A Stock of Dusksteel",
    "detail": "Gather 50 Dusksteel ore.",
    "source": "gains",
    "key": "dusksteel_ore",
    "target": 50,
    "gold": 300,
    "food": 10,
    "scrap": 15,
    "activity": "mine_dusksteel"
  },
  {
    "id": "forge_dawnsteel",
    "title": "Dawnsteel in Your Hands",
    "detail": "Forge your first Dawnsteel Sword.",
    "source": "gains",
    "key": "dawnsteel_sword",
    "target": 1,
    "gold": 600,
    "food": 10,
    "scrap": 40,
    "activity": "craft_dawnsteel_sword"
  },
  {
    "id": "stock_dawnsteel",
    "title": "A Stock of Dawnsteel",
    "detail": "Gather 50 Dawnsteel ore.",
    "source": "gains",
    "key": "dawnsteel_ore",
    "target": 50,
    "gold": 400,
    "food": 10,
    "scrap": 20,
    "activity": "mine_dawnsteel"
  },
  {
    "id": "apex_wilds_1",
    "title": "Bring Down The Briar Marksman",
    "detail": "Defeat The Briar Marksman once.",
    "source": "kills",
    "key": "apex_wilds_1",
    "target": 1,
    "gold": 400,
    "food": 20,
    "scrap": 20,
    "activity": "hunt_apex_wilds_1"
  },
  {
    "id": "apex_wilds_2",
    "title": "Bring Down Mossback Colossus",
    "detail": "Defeat Mossback Colossus once.",
    "source": "kills",
    "key": "apex_wilds_2",
    "target": 1,
    "gold": 800,
    "food": 20,
    "scrap": 40,
    "activity": "hunt_apex_wilds_2"
  },
  {
    "id": "apex_wilds_3",
    "title": "Bring Down The Emberwood Elder",
    "detail": "Defeat The Emberwood Elder once.",
    "source": "kills",
    "key": "apex_wilds_3",
    "target": 1,
    "gold": 1200,
    "food": 20,
    "scrap": 60,
    "activity": "hunt_apex_wilds_3"
  },
  {
    "id": "apex_marsh_1",
    "title": "Bring Down The Chainbound Diver",
    "detail": "Defeat The Chainbound Diver once.",
    "source": "kills",
    "key": "apex_marsh_1",
    "target": 1,
    "gold": 400,
    "food": 20,
    "scrap": 20,
    "activity": "hunt_apex_marsh_1"
  },
  {
    "id": "apex_marsh_2",
    "title": "Bring Down The Lantern Widow",
    "detail": "Defeat The Lantern Widow once.",
    "source": "kills",
    "key": "apex_marsh_2",
    "target": 1,
    "gold": 800,
    "food": 20,
    "scrap": 40,
    "activity": "hunt_apex_marsh_2"
  },
  {
    "id": "apex_marsh_3",
    "title": "Bring Down Leviathan of the Choir",
    "detail": "Defeat Leviathan of the Choir once.",
    "source": "kills",
    "key": "apex_marsh_3",
    "target": 1,
    "gold": 1200,
    "food": 20,
    "scrap": 60,
    "activity": "hunt_apex_marsh_3"
  },
  {
    "id": "apex_crown_1",
    "title": "Bring Down The Ash Executioner",
    "detail": "Defeat The Ash Executioner once.",
    "source": "kills",
    "key": "apex_crown_1",
    "target": 1,
    "gold": 400,
    "food": 20,
    "scrap": 20,
    "activity": "hunt_apex_crown_1"
  },
  {
    "id": "apex_crown_2",
    "title": "Bring Down Bishop of the Last Bell",
    "detail": "Defeat Bishop of the Last Bell once.",
    "source": "kills",
    "key": "apex_crown_2",
    "target": 1,
    "gold": 800,
    "food": 20,
    "scrap": 40,
    "activity": "hunt_apex_crown_2"
  },
  {
    "id": "apex_crown_3",
    "title": "Bring Down The Cinder Sovereign",
    "detail": "Defeat The Cinder Sovereign once.",
    "source": "kills",
    "key": "apex_crown_3",
    "target": 1,
    "gold": 1200,
    "food": 20,
    "scrap": 60,
    "activity": "hunt_apex_crown_3"
  }
]
