extends RefCounted
const ALL = [
  {
    "id": "contract_march_0_1",
    "title": "Clear the Crossing \u00b7 Rimeglass Reach",
    "detail": "Defeat Snowbound Prowler 5 times.",
    "source": "kills",
    "key": "march_0_1",
    "target": 5,
    "gold": 100000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_0_1"
  },
  {
    "id": "contract_march_0_3",
    "title": "Secure the Supply Route \u00b7 Rimeglass Reach",
    "detail": "Defeat Glassback Crab 8 times.",
    "source": "kills",
    "key": "march_0_3",
    "target": 8,
    "gold": 100000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_0_3"
  },
  {
    "id": "contract_march_0_4",
    "title": "Silence the Watch \u00b7 Rimeglass Reach",
    "detail": "Defeat Hoarfrost Sentry 3 times.",
    "source": "kills",
    "key": "march_0_4",
    "target": 3,
    "gold": 100000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_0_4"
  },
  {
    "id": "contract_march_0_6",
    "title": "Recover the Lost Stores \u00b7 Rimeglass Reach",
    "detail": "Defeat Frozen Castellan 10 times.",
    "source": "kills",
    "key": "march_0_6",
    "target": 10,
    "gold": 100000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_0_6"
  },
  {
    "id": "contract_march_0_8",
    "title": "Break the Siege \u00b7 Rimeglass Reach",
    "detail": "Defeat The Winter Abbot 1 times.",
    "source": "kills",
    "key": "march_0_8",
    "target": 1,
    "gold": 100000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_0_8"
  },
  {
    "id": "contract_march_1_1",
    "title": "Clear the Crossing \u00b7 Briarheart Fen",
    "detail": "Defeat Thornback Hound 5 times.",
    "source": "kills",
    "key": "march_1_1",
    "target": 5,
    "gold": 200000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_1_1"
  },
  {
    "id": "contract_march_1_3",
    "title": "Secure the Supply Route \u00b7 Briarheart Fen",
    "detail": "Defeat Briarbound Knight 8 times.",
    "source": "kills",
    "key": "march_1_3",
    "target": 8,
    "gold": 200000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_1_3"
  },
  {
    "id": "contract_march_1_4",
    "title": "Silence the Watch \u00b7 Briarheart Fen",
    "detail": "Defeat Fen Leech 3 times.",
    "source": "kills",
    "key": "march_1_4",
    "target": 3,
    "gold": 200000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_1_4"
  },
  {
    "id": "contract_march_1_6",
    "title": "Recover the Lost Stores \u00b7 Briarheart Fen",
    "detail": "Defeat Thorn Matron 10 times.",
    "source": "kills",
    "key": "march_1_6",
    "target": 10,
    "gold": 200000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_1_6"
  },
  {
    "id": "contract_march_1_8",
    "title": "Break the Siege \u00b7 Briarheart Fen",
    "detail": "Defeat The Briar Regent 1 times.",
    "source": "kills",
    "key": "march_1_8",
    "target": 1,
    "gold": 200000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_1_8"
  },
  {
    "id": "contract_march_2_1",
    "title": "Clear the Crossing \u00b7 Cinderfall Foundry",
    "detail": "Defeat Cinder Carapace 5 times.",
    "source": "kills",
    "key": "march_2_1",
    "target": 5,
    "gold": 300000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_2_1"
  },
  {
    "id": "contract_march_2_3",
    "title": "Secure the Supply Route \u00b7 Cinderfall Foundry",
    "detail": "Defeat Slagbound Keeper 8 times.",
    "source": "kills",
    "key": "march_2_3",
    "target": 8,
    "gold": 300000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_2_3"
  },
  {
    "id": "contract_march_2_4",
    "title": "Silence the Watch \u00b7 Cinderfall Foundry",
    "detail": "Defeat Ash Sifter 3 times.",
    "source": "kills",
    "key": "march_2_4",
    "target": 3,
    "gold": 300000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_2_4"
  },
  {
    "id": "contract_march_2_6",
    "title": "Recover the Lost Stores \u00b7 Cinderfall Foundry",
    "detail": "Defeat Kiln Overseer 10 times.",
    "source": "kills",
    "key": "march_2_6",
    "target": 10,
    "gold": 300000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_2_6"
  },
  {
    "id": "contract_march_2_8",
    "title": "Break the Siege \u00b7 Cinderfall Foundry",
    "detail": "Defeat The Furnace Witness 1 times.",
    "source": "kills",
    "key": "march_2_8",
    "target": 1,
    "gold": 300000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_2_8"
  },
  {
    "id": "contract_march_3_1",
    "title": "Clear the Crossing \u00b7 The Hushed Coast",
    "detail": "Defeat Tidebound Hound 5 times.",
    "source": "kills",
    "key": "march_3_1",
    "target": 5,
    "gold": 400000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_3_1"
  },
  {
    "id": "contract_march_3_3",
    "title": "Secure the Supply Route \u00b7 The Hushed Coast",
    "detail": "Defeat Netbound Sentinel 8 times.",
    "source": "kills",
    "key": "march_3_3",
    "target": 8,
    "gold": 400000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_3_3"
  },
  {
    "id": "contract_march_3_4",
    "title": "Silence the Watch \u00b7 The Hushed Coast",
    "detail": "Defeat Brine Hermit 3 times.",
    "source": "kills",
    "key": "march_3_4",
    "target": 3,
    "gold": 400000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_3_4"
  },
  {
    "id": "contract_march_3_6",
    "title": "Recover the Lost Stores \u00b7 The Hushed Coast",
    "detail": "Defeat Blackwake Keeper 10 times.",
    "source": "kills",
    "key": "march_3_6",
    "target": 10,
    "gold": 400000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_3_6"
  },
  {
    "id": "contract_march_3_8",
    "title": "Break the Siege \u00b7 The Hushed Coast",
    "detail": "Defeat The Tidemarked King 1 times.",
    "source": "kills",
    "key": "march_3_8",
    "target": 1,
    "gold": 400000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_3_8"
  },
  {
    "id": "contract_march_4_1",
    "title": "Clear the Crossing \u00b7 Gloamwood Crossing",
    "detail": "Defeat Barkhide Prowler 5 times.",
    "source": "kills",
    "key": "march_4_1",
    "target": 5,
    "gold": 500000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_4_1"
  },
  {
    "id": "contract_march_4_3",
    "title": "Secure the Supply Route \u00b7 Gloamwood Crossing",
    "detail": "Defeat Needleback Spider 8 times.",
    "source": "kills",
    "key": "march_4_3",
    "target": 8,
    "gold": 500000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_4_3"
  },
  {
    "id": "contract_march_4_4",
    "title": "Silence the Watch \u00b7 Gloamwood Crossing",
    "detail": "Defeat Hollowwood Knight 3 times.",
    "source": "kills",
    "key": "march_4_4",
    "target": 3,
    "gold": 500000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_4_4"
  },
  {
    "id": "contract_march_4_6",
    "title": "Recover the Lost Stores \u00b7 Gloamwood Crossing",
    "detail": "Defeat Veilbound Keeper 10 times.",
    "source": "kills",
    "key": "march_4_6",
    "target": 10,
    "gold": 500000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_4_6"
  },
  {
    "id": "contract_march_4_8",
    "title": "Break the Siege \u00b7 Gloamwood Crossing",
    "detail": "Defeat The Last Huntsman 1 times.",
    "source": "kills",
    "key": "march_4_8",
    "target": 1,
    "gold": 500000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_4_8"
  },
  {
    "id": "contract_march_5_1",
    "title": "Clear the Crossing \u00b7 The Starless Bastion",
    "detail": "Defeat Voidbound Hound 5 times.",
    "source": "kills",
    "key": "march_5_1",
    "target": 5,
    "gold": 600000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_5_1"
  },
  {
    "id": "contract_march_5_3",
    "title": "Secure the Supply Route \u00b7 The Starless Bastion",
    "detail": "Defeat Chainless Knight 8 times.",
    "source": "kills",
    "key": "march_5_3",
    "target": 8,
    "gold": 600000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_5_3"
  },
  {
    "id": "contract_march_5_4",
    "title": "Silence the Watch \u00b7 The Starless Bastion",
    "detail": "Defeat Astral Husk 3 times.",
    "source": "kills",
    "key": "march_5_4",
    "target": 3,
    "gold": 600000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_5_4"
  },
  {
    "id": "contract_march_5_6",
    "title": "Recover the Lost Stores \u00b7 The Starless Bastion",
    "detail": "Defeat Starless Adjudicator 10 times.",
    "source": "kills",
    "key": "march_5_6",
    "target": 10,
    "gold": 600000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_5_6"
  },
  {
    "id": "contract_march_5_8",
    "title": "Break the Siege \u00b7 The Starless Bastion",
    "detail": "Defeat The Night Without End 1 times.",
    "source": "kills",
    "key": "march_5_8",
    "target": 1,
    "gold": 600000,
    "food": 0,
    "scrap": 30,
    "activity": "hunt_march_5_8"
  },
  {
    "id": "contract_guard_0",
    "title": "An Unbroken Seal \u00b7 The Glass Leviathan",
    "detail": "Defeat The Glass Leviathan.",
    "source": "kills",
    "key": "march_guard_0",
    "target": 1,
    "gold": 1000000,
    "food": 0,
    "scrap": 80,
    "activity": "hunt_march_guard_0"
  },
  {
    "id": "contract_guard_1",
    "title": "An Unbroken Seal \u00b7 The Thornless Sovereign",
    "detail": "Defeat The Thornless Sovereign.",
    "source": "kills",
    "key": "march_guard_1",
    "target": 1,
    "gold": 2000000,
    "food": 0,
    "scrap": 80,
    "activity": "hunt_march_guard_1"
  },
  {
    "id": "contract_guard_2",
    "title": "An Unbroken Seal \u00b7 The Unquenched Anvil",
    "detail": "Defeat The Unquenched Anvil.",
    "source": "kills",
    "key": "march_guard_2",
    "target": 1,
    "gold": 3000000,
    "food": 0,
    "scrap": 80,
    "activity": "hunt_march_guard_2"
  },
  {
    "id": "contract_guard_3",
    "title": "An Unbroken Seal \u00b7 The Pale Undertow",
    "detail": "Defeat The Pale Undertow.",
    "source": "kills",
    "key": "march_guard_3",
    "target": 1,
    "gold": 4000000,
    "food": 0,
    "scrap": 80,
    "activity": "hunt_march_guard_3"
  },
  {
    "id": "contract_guard_4",
    "title": "An Unbroken Seal \u00b7 The Keeper of No Names",
    "detail": "Defeat The Keeper of No Names.",
    "source": "kills",
    "key": "march_guard_4",
    "target": 1,
    "gold": 5000000,
    "food": 0,
    "scrap": 80,
    "activity": "hunt_march_guard_4"
  }
]
