extends "res://tests/capture31.gd"
const U=preload("res://ui/style.gd")
func capture():
 root.size=Vector2i(412,892)
 var scene=PreviewApp.new();root.add_child(scene);scene.set_process(false)
 scene.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT);scene.mode="play"
 var m=preload("res://tests/balance43.gd").build("warden",false)
 for id in m.data.enemies:m.s.kills[id]=5
 m.s.experience.coach_active=false;scene.model.s=m.s.duplicate(true)
 m=scene.model
 for character in ["frostbound","penitent","duskblade"]:
  m.s.hero["class"]=character
  scene.set_page("character")
  await snap("hero-"+character+"-0.50")
 preload("res://ui/marches.gd").new(scene).open(0)
 await snap("marches-0.50")
 preload("res://ui/marches.gd").new(scene).equipment(0)
 await snap("regional-equipment-0.50")
 m.gain("card_ash_rat",1)
 preload("res://ui/cards.gd").new(scene).detail("card_ash_rat")
 await snap("card-slots-0.50")
 preload("res://ui/cards.gd").new(scene).choose_equipment("card_ash_rat")
 assert(button_text(scene,"Legendary Dawnsteel Sword")==null)
 await snap("matching-card-equipment-0.50")
 scene.talents_dialog()
 await snap("talents-0.50")
 preload("res://ui/runeforge.gd").new(scene).forge("rime")
 await snap("runes-0.50")
 preload("res://ui/masterworks.gd").new(scene).research()
 await snap("research-0.50")
 scene.dismiss();scene.skill="smithing";scene.show_locked_recipes=true;scene.set_page("skills")
 assert(button_text(scene,"Next")!=null)
 await snap("recipes-0.50")
 m.command({"type":"clear"});m.command({"type":"queue","id":"hunt_march_0_0","target":3});m.advance(6500)
 scene.set_page("explore")
 await snap("battle-0.50")
 m.command({"type":"clear"});m.command({"type":"queue","id":"mine_copper","target":100});scene.set_page("village")
 await snap("work-0.50")
 root.size=Vector2i(360,800);U.scale=1.3;scene.refresh_shell()
 preload("res://ui/cards.gd").new(scene).detail("card_march_5_8")
 await snap("card-large-0.50")
 preload("res://ui/marches.gd").new(scene).open(5)
 await snap("marches-large-0.50")
 print("CAPTURE50 PASS: heroes, regions, restricted cards, talent/rune UI, research, bounded recipes, battle/work, large text")
 quit()
