extends "res://tests/capture.gd"
func capture():
	root.size = Vector2i(480,960)
	var scene = PreviewApp.new()
	root.add_child(scene)
	scene.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	scene.set_process(false)
	scene.mode = "play"
	var training = preload("res://ui/training.gd").new(scene)
	training.open("smithing",25,15)
	await snap("training-plan-0.29")
	scene.dialog_footer.get_children()[0].emit_signal("pressed")
	assert(scene.model.s.training_goal.target==25 and not scene.model.s.queue.is_empty())
	training.open("smithing",25,15)
	scene.toast_label.hide()
	await snap("training-existing-work-0.29")
	scene.model.advance(900000)
	scene.dismiss()
	scene.set_page("skills")
	scene.toast_label.hide()
	await snap("training-saved-goal-0.29")
	training.open("smithing",25,60)
	await snap("training-next-batch-0.29")
	scene.U.scale = 1.3
	root.size = Vector2i(360,800)
	training.open("mining",100,240)
	await snap("training-narrow-0.29")
	print("UI 29: actual training start, preserved queue, saved Skills goal and narrow plan captured")
	quit()
