extends "res://tests/capture31.gd"

func capture():
	root.size=Vector2i(360,800)
	var scene=PreviewApp.new();root.add_child(scene)
	scene.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT);scene.set_process(false)
	scene.U.scale=1.3;scene.model.s.tutorial=true
	scene.model.s.experience.coach_active=false
	scene.set_page("explore")
	scene.activity_dialog("hunt_ash_rat",1)
	scene.toast_label.hide()
	await snap("hunt-clean-narrow-0.44")
	var toggle=button_text(scene.dialog,"Show enemy & loot details")
	assert(toggle!=null)
	toggle.pressed.emit()
	assert(toggle.text=="Hide enemy & loot details")
	await snap("hunt-details-narrow-0.44")
	toggle.pressed.emit()
	assert(toggle.text=="Show enemy & loot details")
	var begin=button_text(scene.dialog,"Begin · 1 fight")
	assert(begin!=null and not begin.disabled)
	begin.pressed.emit()
	assert(not scene.model.s.fight.is_empty())
	scene.model.command({"type":"clear"})
	for id in scene.model.data.enemies: scene.model.s.kills[id]=1
	preload("res://ui/cards.gd").new(scene).detail("card_frontier_2_5")
	await snap("card-clean-narrow-0.44")
	preload("res://ui/masterworks.gd").new(scene).open(1)
	await snap("masterworks-clean-narrow-0.44")
	var bestiary=preload("res://ui/bestiary.gd").new(scene)
	bestiary.open()
	assert(button_text(scene.dialog,"Next enemies")!=null)
	button_text(scene.dialog,"Next enemies").pressed.emit()
	assert(button_text(scene.dialog,"Previous enemies")!=null)
	bestiary.open("frontier_2")
	assert(button_text(scene.dialog,"Next enemies")==null)
	await snap("bestiary-clean-narrow-0.44")
	scene.activity_dialog("craft_copper_sword",1)
	await snap("craft-clean-narrow-0.44")
	print("PASS compact hunt toggle and Begin, bestiary pagination/frontier filter, six narrow captures")
	quit()
