extends "res://tests/capture31.gd"

func capture():
	var m = RealmModel.new()
	m.s.tutorial = true
	RealmStamina.state(m).value = 19
	assert(m.command({"type":"queue","id":"hunt_ash_rat","target":3}))
	assert(m.s.stamina.paused and m.s.fight.is_empty())
	m.advance(60000)
	assert(RealmStamina.wait_ms(m,21)==300000)
	assert(RealmStamina.resume_reason(m).contains("2 more stamina"))
	var before = m.s.duplicate(true)
	assert(not m.command({"type":"stamina_resume"}))
	assert(m.s==before,"Premature resume must preserve queue, stamina and pause")
	root.size = Vector2i(360,800)
	var scene = PreviewApp.new()
	root.add_child(scene)
	scene.set_anchors_and_offsets_preset(Control.PRESET_FULL_RECT)
	scene.set_process(false)
	scene.U.scale = 1.3
	scene.model.s = m.s.duplicate(true)
	preload("res://ui/stamina.gd").new(scene).open()
	scene.toast_label.hide()
	var resume = scene.dialog.find_child("ResumeHunting",true,false)
	assert(resume.disabled and resume.visible)
	await snap("rest-waiting-0.42")
	scene.model.advance(300000)
	scene.refresh()
	assert(not resume.disabled and scene.model.s.fight.is_empty())
	assert(RealmStamina.resume_reason(scene.model)=="")
	await snap("rest-ready-0.42")
	resume.pressed.emit()
	assert(not scene.model.s.fight.is_empty() and not is_instance_valid(scene.dialog))
	assert(RealmStamina.resume_reason(scene.model)=="Your hunt is already running.")
	assert(not scene.model.command({"type":"stamina_resume"}))
	scene.model.command({"type":"clear"})
	preload("res://ui/stamina.gd").new(scene).open()
	assert(not scene.dialog.find_child("ResumeHunting",true,false).visible)
	await snap("rest-no-hunt-0.42")
	assert(RealmStamina.wait_ms(scene.model,0)==0)
	var save = RealmSave.new()
	assert(not save.decode(save.encode(scene.model.s),scene.model.data).is_empty())
	print("PASS next-hunt countdown, safe resume, live button readiness, no automatic resume, empty queue and save")
	quit()
