extends SceneTree
func _init():
	var m = RealmModel.new()
	var store = RealmSave.new()
	var before = m.s.duplicate(true)
	var short_goal = RealmTraining.plan(m,"smithing",2,60)
	assert(short_goal.error=="" and short_goal.cycles==1 and short_goal.level_after==2)
	var plan = RealmTraining.plan(m,"smithing",25,15)
	assert(plan.error=="" and plan.seconds<=900 and plan.cycles<=1000 and plan.level_after<25)
	assert(m.s==before)
	assert(plan.steps.size()>1)
	var xp = int(m.s.xp.smithing)
	assert(m.command({"type":"training","id":"smithing","target":25,"minutes":15}))
	var queued = m.s.queue.duplicate(true)
	assert(not m.command({"type":"training","id":"mining","target":25,"minutes":60}) and m.s.queue==queued)
	assert(not store.decode(store.encode(m.s),m.data).is_empty())
	m.advance(900000)
	assert(m.s.queue.is_empty() and m.s.xp.smithing-xp==plan.xp and m.level("smithing")==plan.level_after)
	assert(m.s.training_goal.target==25)
	var next = RealmTraining.plan(m,"smithing",25,60)
	assert(next.error=="")
	assert(m.command({"type":"training","id":"smithing","target":25,"minutes":60}))
	var copy = RealmModel.new()
	copy.s = store.decode(store.encode(m.s),copy.data)
	m.advance(3600000)
	for i in range(360): copy.advance(10000)
	assert(store.decode(store.encode(m.s),m.data)==store.decode(store.encode(copy.s),copy.data))
	assert(m.command({"type":"training_clear"}) and not m.s.has("training_goal"))
	m.s.training_goal = {"skill":"missing","target":25,"minutes":60}
	assert(store.decode(store.encode(m.s),m.data).is_empty())
	m.s.erase("training_goal")
	for skill in m.data.skills: m.s.xp[skill] = 245025
	assert(RealmTraining.plan(m,"mining",100,15).get("complete",false))
	print("TRAINING 29: dependency XP/time preview, bounded batch, non-mutating preview, queue preservation, persistent goal, save validation and offline equivalence PASS")
	print("First Smithing batch: ",plan.activity," x",plan.cycles,"; ",plan.seconds,"s; XP ",plan.xp,"; level ",plan.level_after)
	quit()
